### ISSUE TITLE
Examples fail to build

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm-examples#1]
Since the recent update I can't get any of the examples to build. transactions, jaxrs and messaging, for instance, all fail with the following output from mvn package:

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm Examples: Messaging 1.0.0.Alpha02-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.117s
[INFO] Finished at: Sat Jun 06 17:10:06 BST 2015
[INFO] Final Memory: 5M/103M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha3-SNAPSHOT or one of its dependencies could not be resolved: Failure to find org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha3-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

Using -U to force a refresh still gives:

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WildFly Swarm Examples: Messaging 1.0.0.Alpha02-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/wildfly/swarm/wildfly-swarm-plugin/1.0.0.Alpha3-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/wildfly/swarm/wildfly-swarm-plugin/1.0.0.Alpha3-SNAPSHOT/wildfly-swarm-plugin-1.0.0.Alpha3-SNAPSHOT.pom
[WARNING] The POM for org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha3-SNAPSHOT is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/wildfly/swarm/wildfly-swarm-plugin/1.0.0.Alpha3-SNAPSHOT/wildfly-swarm-plugin-1.0.0.Alpha3-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.869s
[INFO] Finished at: Sat Jun 06 17:11:13 BST 2015
[INFO] Final Memory: 9M/103M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha3-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha3-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]

Running on Mac OS 10.9.5 with ...

rorschach:messaging marklittle$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 16:22:22+0100)
Maven home: /usr/local/Cellar/maven/3.1.1/libexec
Java version: 1.7.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/1.7.0.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

**Comment by arun-gupta** [comment]
@nmcl Have you built the workspace locally?

**Comment by kenfinnigan** [comment]
After tagging Alpha2 we updated the version for WildFly Swarm in the examples to use the latest snapshot. This is likely caused by WildFly Swarm not being built locally first.

I see a couple of options:
* Add a link in readme of examples root pointing to latest tagged version to clone or download
* Explicitly override WildFly Swarm version for any examples that require a newer version than the most recent release

**Comment by jamezp** [comment]
Another option might be to have a experimental-examples repo that contains the examples that require a `SNAPSHOT`.

**Comment by kenfinnigan** [comment]
That might get messy with merging them back into the main repo.

That did give me the idea to have an experimental branch of repo, and readme on master could have section for examples that need HEAD to work, with links to them in experimental branch

**Comment by jamezp** [comment]
Ah yeah that makes sense.

**Comment by bobmcwhirter** [comment]
The examples are tagged at 1.0.0.alpha2. 

--

**Comment by nmcl** [comment]
I'll just build everything locally for now.

**Comment by nmcl** [comment]
At the very least it's worth adding something to the examples README that either mandates (instructs) people to build -swarm locally from the start, no matter which examples they may be going to run, or mentioned which ones need a local build.
