### ISSUE TITLE
Add extended Narayana example

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm-examples#16]
I'm working on this to showcase some of the extended capabilities we have in Narayana. Creating issue here so I can track.

**Comment by bobmcwhirter** [comment]
PTO

--

**Comment by nmcl** [comment]
Making some progress ...

https://github.com/nmcl/wfswarm-example-arjuna

**Comment by nmcl** [comment]
Made examples (war only).

https://github.com/nmcl/swarm-examples/tree/master/arjuna

**Comment by kenfinnigan** [comment]
Moved to https://issues.jboss.org/browse/SWARM-239
