### ISSUE TITLE
Create a swarm soap web service example

### ISSUE THREAD

**Issue by kylinsoong** [wildfly-swarm/wildfly-swarm-examples#22]
I am not find a example that demonstrates soap web service as
    https://github.com/wildfly/quickstart/tree/9.x/helloworld-ws
can we create one?

**Comment by kenfinnigan** [comment]
We welcome contributions!

Go ahead and create one. We can help out if there are problems

Ken

**Comment by emag** [comment]
I'm not sure whether it needs webservices fraction.

Creating initial webservices fraction.
https://github.com/wildfly-swarm/wildfly-swarm/pull/72

**Comment by kenfinnigan** [comment]
It might.

You can take a look at finalizing the PR to make it work.

**Comment by emag** [comment]
@kylinsoong I just did p-r jax-ws example. please check it out.

https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jaxws

**Comment by kylinsoong** [comment]
@emag thanks.
