### ISSUE TITLE
Problem with jpa jax-rs example

### ISSUE THREAD

**Issue by Snugglepantz** [wildfly-swarm/wildfly-swarm-examples#27]
I attempted to get this example to work but had an issue with the datasource.  I created a working version by adding <jta-data-source>java:jboss/datasources/MyDS</jta-data-source> to persistence.xml.  There is an example here https://github.com/Snugglepantz/swarm-server/blob/master/src/main/resources/META-INF/persistence.xml

**Comment by emag** [comment]
Are you using WF-Swarm head?
Perhaps it is same problem the following issue.

https://github.com/wildfly-swarm/wildfly-swarm/issues/135

**Comment by kenfinnigan** [comment]
@Snugglepantz can you provide a link to a stacktrace?

I've just run the jpa-jaxrs-cdi example against latest HEAD of master and it worked fine. Can you confirm which version of WIldFly Swarm you are running the example against? HEAD or Alpha4?

**Comment by emag** [comment]
@kenfinnigan  @Snugglepantz 's application is kind of jpa-jaxrs-cdi-`shrinkwrap`. 

And https://github.com/wildfly-swarm/wildfly-swarm/issues/135 is reproducible at HEAD.

**Comment by kenfinnigan** [comment]
The issue of DS configuration in persistence.xml is because https://github.com/Snugglepantz/swarm-server/blob/master/src/main/java/me/slashfix/swarm/Main.java#L33 is commented out.

Without those lines, JPA doesn't know what Datasource to use for persistence.

**Comment by emag** [comment]
@kenfinnigan Yes, It's correct, however, it's another problem. 

wildfly-swarm/wildfly-swarm#135 `LinkageError` is thrown at even jpa-jaxrs-cdi-shrinkrwap example.

wf-swarm commit id: https://github.com/wildfly-swarm/wildfly-swarm/commit/a14bfc40cf12c455fe10a99c04dfe1e1367cfab2 (HEAD)
example commit id: 24d0e88(HEAD)

**Comment by Snugglepantz** [comment]
@emag I was using head, I did run into a few problems building but I eventually got it

**Comment by kenfinnigan** [comment]
This should now be fixed in latest HEAD

Can you verify @Snugglepantz

**Comment by Snugglepantz** [comment]
@kenfinnigan The jpa jaxrs cdi works for me now.  I was trying the shrinkwrap example, is there a reason to use one over the other?

**Comment by kenfinnigan** [comment]
The main difference is the presence of a class with main() to create the container and configure the fractions.

If default configuration is all you need, then you don't need the shrinkwrap version

Ken

**Comment by Snugglepantz** [comment]
Thanks for the information!
