### ISSUE TITLE
jpa-jaxrs-cdi JTA issues

### ISSUE THREAD

**Issue by Salaboy** [wildfly-swarm/wildfly-swarm-examples#33]
It seems that the project can query the DB correctly but as soon as you try to persist an object using JPA it will fail due the lack of transactions configurations. Do you know what configuration is needed to get that working?

**Comment by emag** [comment]
Hmm, it's strange. I created jpa-jaxrs-cdi`-shrinkwarp` CRUD application, and it works.
> Also, war applications should work.

https://github.com/emag/wildfly-swarm-quickstarts/tree/master/jaxrs-cdi-jpa

Can you share your project?

**Comment by Salaboy** [comment]
I will try the shrinkwrap option to see if it works as expected.

**Comment by emag** [comment]
just now I checked `war` version, and it works.

**Comment by Salaboy** [comment]
Yes, I notice the @Transactional annotation.. and the PU that is not using JTA, is that kinda wrong right? I mean.. if we are running in a Wildfly container with JTA and the datasource is a JTA datasource, shouldn't we run with a JTA PU and without having to annotate the @Transactional methods? Maybe what I'm looking for is a way to is just to have stateless beans there (@Stateless). 

I guess that adding arquillian to your project will be great... so we can show how to test the code. Wdyt? I'm having a lot of issues in setting up a test case for a very similar project than the one that you have here.

**Comment by emag** [comment]
Did you get the following exception?
``` sh
TransactionRequiredException: WFLYJPA0060:
Transaction is required to perform this operation
(either use a transaction or extended persistence context)
```

> if we are running in a Wildfly container with JTA and the datasource is a JTA datasource, shouldn't we run with a JTA PU and without having to annotate the @Transactional methods?

Are you using CDI + JTA just like my sample? if so, yes. `em#persist,merge,remove` must join transaction as the exception said. CDI container don't begin transactions automatically.

> Maybe what I'm looking for is a way to is just to have stateless beans there (@Stateless). 

Yes, Using EJBs  is a standard manner to use Container Managed Transactions(CMT) at least until Java EE 6. Thanks to Java EE 7(JTA 1.2) `@ javax.transaction.Transactional`, we can manage transactions on CDI Managed Bean.

You can add @ Transactional to a class, it may be useful.

https://docs.oracle.com/javaee/7/api/javax/transaction/Transactional.html

> I guess that adding arquillian to your project ...

Thank you for your proposals! But, I would prefer contributing some WildFly Swarm repositories to adding my repository, which is my own (maybe experimental) one...
I think official examples are very useful for all WildFly Swarm users.

How about adding tests to wildfly-swarm-examples, or booker?

**Comment by Salaboy** [comment]
Thanks for pointing the new JTA 1.2 annotation.. I will use that for now...
And yes.. we should provide arquillian tests to wildfly-swarm-examples, so we can make sure that the configurations that are running in wildfly swarm can be tested.

**Comment by kenfinnigan** [comment]
From the comments it looks like this is resolved.

Please open an issue here: https://issues.jboss.org/browse/SWARM if that is not the case
