### ISSUE TITLE
Version 1.0.0.0.Alpha6-SNAPSHOT examples reference invalid artifact versions that should be 1.0.0.Alpha4

### ISSUE THREAD

**Issue by matteg** [wildfly-swarm/wildfly-swarm-examples#36]
Version 1.0.0.0.Alpha6-SNAPSHOT examples uses the parent POM version but the required version of many artifacts is 1.0.0.Alpha4

[ErrorOnExecution.txt](https://github.com/wildfly-swarm/wildfly-swarm-examples/files/33297/ErrorOnExecution.txt)

**Comment by kenfinnigan** [comment]
I think this is now resolved.

If that's not the case, please open an issue at https://issues.jboss.org/browse/SWARM
