### ISSUE TITLE
An example with postgres

### ISSUE THREAD

**Issue by davidillsley** [wildfly-swarm/wildfly-swarm-examples#39]
I'm sure its trivial, but I can't find any documentation on how to use a real database eg postgres rather than h2, and my naiive attempts aren't working. An example would be really useful.

**Comment by emag** [comment]
I agree with you. For now you can check my example using postgresql.

https://github.com/emag/wildfly-swarm-tour/tree/master/complete/lifelog-postgresql

you need to :

* add module.xml for postgresql jdbc driver like full brown wildfly
  * https://github.com/emag/wildfly-swarm-tour/tree/master/complete/lifelog-postgresql/src/main/resources/modules/org/postgresql/main
* setup Datasource Fraction
 * https://github.com/emag/wildfly-swarm-tour/blob/master/complete/lifelog-postgresql/src/main/java/wildflyswarmtour/lifelog/LifeLogContainer.java#L18-L30

I'll do p-r more simple example to this repository later.

**Comment by kenfinnigan** [comment]
Moved to https://issues.jboss.org/browse/SWARM-240
