### ISSUE TITLE
Examples using a `static` folder don't compile in Eclipse

### ISSUE THREAD

**Issue by fbricon** [wildfly-swarm/wildfly-swarm-examples#45]
`example-static-shrinkwrap`and `example-static-war` contain ITs under a `static` folder. The classes declare a package that doesn't match the expected folder. I have no idea how this can work in command line but Eclipse is pretty upset about it:
 
![](http://content.screencast.com/users/fbricon/folders/Jing/media/74caeb54-fda7-4abe-9655-25a7e84547ab/00000271.png)

Could you please use a more standard package layout?

**Comment by bobmcwhirter** [comment]
Yah, we're slowly going through the examples and adding them back in.

That one shouldn't yet be listed in the <modules> of the top pom.  Eclipse doesn't know to ignore it?

**Comment by fbricon** [comment]
the root pom lists `<module>static</module>` so the projects are imported by eclipse

**Comment by bobmcwhirter** [comment]
Well dang. We'll fix!
