### ISSUE TITLE
Transactions.war build warning ...

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm-examples#46]
[WARNING] Could not transfer metadata org.wildfly.swarm:container-modules:1.0.0.Alpha6-SNAPSHOT/maven-metadata.xml from/to jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/): java.lang.RuntimeException: Could not generate DH keypair

On Mac OS X with ...

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.7.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/1.7.0.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

**Comment by bobmcwhirter** [comment]
While we require repository.jboss.org for some artifacts, our artifacts are
not held there.

Given that Maven attempts to find metadata from *every* known repository,
you’ll see some of these warnings.  They are only warnings, though, and do
not cause any problems.

Though, I’m confused about the DH keypair issue.  Do you have a large
stack, if one was produced?

**Comment by nmcl** [comment]
I can email you the entire build output if you want, or attach it here. Let me know which.

**Comment by bobmcwhirter** [comment]
gist it and attach the gist url.

Did it fail? or just warn?

**Comment by nmcl** [comment]
It failed but not due to that afaict

https://gist.github.com/nmcl/03c593eec9c8dda2f37a
