### ISSUE TITLE
Problem with access property file

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm-examples#47]
I'm not entirely sure if this is a problem with my example (trying to access non-Java EE APIs), configuration of it, WildFly-Swarm, or something else entirely. However, hopefully this other issue gives some context as any help would be appreciated ...

https://github.com/nmcl/wfswarm-example-arjuna/issues/1

**Comment by kenfinnigan** [comment]
Moved to https://issues.jboss.org/browse/SWARM-241
