### ISSUE TITLE
JAX-RS war example fails to build

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm-examples#49]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2015-12-24T16:11:45+00:00
[INFO] Final Memory: 34M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-jaxrs-war: Could not resolve dependencies for project org.wildfly.swarm.examples:example-jaxrs-war:war:1.0.0.Alpha6-SNAPSHOT: Failure to find org.wildfly.swarm.examples:examples-base:jar:1.0.0.Alpha6-SNAPSHOT in https://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]

**Comment by nmcl** [comment]
https://gist.github.com/nmcl/37fd44ff343a77545532

**Comment by emag** [comment]
At first, you need to `mvn install (-DskipTests)` on top directory because -swarm-examples depend on examples-base project.

**Comment by bobmcwhirter** [comment]
Or as with the other, mvn install inside base/ first and then you can build each individually.

**Comment by nmcl** [comment]
OK, will try both. Didn't see this mentioned in the README ;) [Yeah, I could be blind!]

**Comment by bobmcwhirter** [comment]
It may not be. I think you have commit rights if you want to add what you learn. Fresh eyes are good since we are blind to our own assumptions and knowledge.

**Comment by nmcl** [comment]
You're right ... good point :)

**Comment by nmcl** [comment]
Done.
